export const RESPONSE_SUCCESS = 'RESPONSE_SUCCESS';
export const RESPONSE_REDIRECT = 'RESPONSE_REDIRECT';
export const RESPONSE_BAD_REQUEST = 'RESPONSE_BAD_REQUEST';
export const RESPONSE_METHOD_NOT_ALLOWED = 'RESPONSE_METHOD_NOT_ALLOWED';
export const RESPONSE_NOT_FOUND = 'RESPONSE_NOT_FOUND';
export const RESPONSE_FORBIDDEN = 'RESPONSE_FORBIDDEN';
export const RESPONSE_SERVER = 'RESPONSE_SERVER';
export const ENQUEUE_SCRIPT = 'ENQUEUE_SCRIPT';